---
name: LC build and push to ghcr.io

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    name: Builds new NetBox Docker Images
    strategy:
      matrix:
        build_cmd:
          - ./build.sh develop
        platform:
          - linux/amd64
    env:
      GH_ACTION: enable
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      IMAGE_NAMES: ghcr.io/${{ github.repository }}
    steps:
      - id: source-checkout
        name: Checkout
        uses: actions/checkout@v4
      - id: set-netbox-docker-version
        name: Get Version of NetBox Docker
        run: echo "version=$(cat VERSION)" >>"$GITHUB_OUTPUT"
        shell: bash
      - id: qemu-setup
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - id: buildx-setup
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      # ghcr.io
      - id: ghcr-io-login
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
        if: steps.docker-build.outputs.skipped != 'true'
      - id: build-and-push
        name: Push the image
        run: ${{ matrix.build_cmd }} --push
        if: steps.docker-build.outputs.skipped != 'true'
        env:
          BUILDX_PLATFORM: ${{ matrix.platform }}
          BUILDX_BUILDER_NAME: ${{ steps.buildx-setup.outputs.name }}      
